services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: always
    ports:
      - "8020:8080"
    command: --auth=password
    volumes:
      - ./code-server/.config:/home/coder/.config
      - ./code-server/.data:/home/coder/project
      - ./code-server/.local:/home/coder/.local
    environment:
      - PASSWORD=${PASSWORD}
      - TZ=Asia/Tokyo
