services:
  front:
    image: ghcr.io/syou551/file-uploader-front:latest
    env_file:
      - ./front/.env.local
    working_dir: /node/FileUploader/front/dir-share
  back:
    image: ghcr.io/syou551/file-uploader-back:latest
    env_file:
      - ./back/.env
    working_dir: /go/src/FileUploader/back
    volumes:
      - ./.tmp:/tmp/share
    command: bash -c "./main"
    restart: always
  nginx:
    image: ghcr.io/syou551/file-uploader-back:latest
    depends_on:
      - front
      - back
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.7.1
    command:
      - --provider=keycloak-oidc
      - --oidc-issuer-url=http://auth.syou551.dev/realms/auth
      - --client-id=fileUploader
      - --client-secret=${CLIENT_SECRET}
      - --cookie-secret=${COOKIE_SECRET}
      - --redirect-url=https://fileup.syou551.dev/oauth2/callback
      - --upstream=http://nginx:80
      - --email-domain=*
      - --http-address=0.0.0.0:4180
      - --errors-to-info-log
      - --cookie-secure=false
      - --reverse-proxy=true
      - --allowed-role=admin
      - --whitelist-domain=auth.syou551.dev
    ports:
      - "8080:4180"
    depends_on:
      - nginx
    
