services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8050:8000"
    command: cd /node/dirShareApp/front/dir-share | npm run start
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes: 
      - /tmp/share:/go
    ports:
      - "8060:80"
    command: cd /go/src/dirShareApp/back | ./main
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - front
      - back
    ports:
      - "8010:8080"
    