services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    working_dir: /node/dirShareApp/front/dir-share
    command: npm run start
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    working_dir: /go/src/dirShareApp/back
    volumes:
      - ./.tmp:/tmp/share
    command: bash -c "./main"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - front
      - back
    ports:
      - "8080:80"
    