apiVersion: v1
data:
  KEYCLOAK_ID: fileUploader
  KEYCLOAK_ISSUER: http://meruto.tailbfa95.ts.net:8010/realms/auth
  KEYCLOAK_SECRET: 8ZwTDKfeRBASsO2QfA7dTpoOMFfZhjq2
  NEXT_PUBLIC_BACK_URL: http://100.84.142.102:8080
  NEXT_PUBLIC_FRONT_URL: http://100.84.142.102:8080
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: 83132683863-2snl6lauk3ppct0l50j42gjj2nc6honu.apps.googleusercontent.com
  NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: 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
  NEXT_PUBLIC_NEXTAUTH_SECRET: 0/JZntSQXbw8rK+hc6SZJZOETID2Tn+OSQWJnC+VJ/0=
  NEXTAUTH_URL: http://100.84.142.102:8080
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: front-front-env-local
  name: front-env-local
