apiVersion: v1
data:
  mongodb-init-replica-set.js: |
    /* eslint-disable no-undef */

    rs.initiate({ _id: 'overleaf', members: [{ _id: 0, host: 'mongo:27017' }] })
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: mongo
  name: mongo-cm1
