apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: sharelatex-claim0
  name: sharelatex-claim0
spec:
  storageClassname: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
