apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: code-server-claim2
  name: code-server-claim2
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
