repositories:

- name: csi-driver-nfs
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts

releases:

- name: csi-driver-nfs
  namespace: kube-system
  chart: csi-driver-nfs/csi-driver-nfs
  version: v4.9.0
  values:
  - storageClass:
      create: true
      name: nfs-csi
      parameters:
        server: nfs-server-svc.default.svc.cluster.local # NFSサーバのServiceリソースのホスト名を指定
        share: /         # /exports ではなくて / を指定する
      mountOptions:
      - nfsvers=4.1
